Lint/AmbiguousRegexpLiteral:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

